"""add clients

Revision ID: 7573d37dcac3
Revises: 223e07f0a124
Create Date: 2024-06-21 18:16:09.716404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7573d37dcac3'
down_revision = '223e07f0a124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('mobile', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('roll')
    )
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=200), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_index('ix_book_author')
        batch_op.drop_index('ix_book_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.create_index('ix_book_title', ['title'], unique=True)
        batch_op.create_index('ix_book_author', ['author'], unique=False)
        batch_op.alter_column('description',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('author',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.drop_column('image_url')

    op.drop_table('client')
    # ### end Alembic commands ###
